(function(q){(function(f){var l;if(void 0===f.wjs||"[$version]"!==f.wjs.version)l=function(){this.extendObject(this,{context:f,window:f.window||window,document:f.document||window.document,version:"[$version]",readyCallbacks:[],readyComplete:!1,packageDefault:null,loaders:{},loadersExtra:[],loadersBasic:[],extLoaded:{WjsLoader:{}},extRequire:{},processProto:null,processes:[],classProtos:{},classMethods:{},destroyQ:[],cacheBuffer:{},settings:null,linkReg:/^wjs:\/\/([a-zA-Z0-9]*):([a-zA-Z0-9]*)$/});
this.context.wjsContext=f},l.prototype={init:function(a){var b=this;this.window.addEventListener("load",function(){b.extendObject(b,a);for(var c=0;c<b.loadersBasic.length;c++)b.loaderAdd(b.loadersBasic[c],void 0,!0);b.ready(function(){b.linksInit(b.document.body)});(new b.processProto({complete:function(){delete b.packageDefault;b.readyComplete=!0;b.callbacks(b.readyCallbacks)}})).responseParse(b.packageDefault)})},ready:function(a){!0===this.readyComplete?this.window.setTimeout(function(){a()}):
this.readyCallbacks.push(a)},callbacks:function(a,b){for(var c=0;c<a.length;c++)a[c].apply(this,b)},linksInit:function(a){a=a.querySelectorAll('a[href^="wjs://"]');for(var b=0,c,d=function(){return!1};b<a.length;b++)c=a[b].getAttribute("href"),a[b].setAttribute("href","#"),a[b].onclick=d,a[b].setAttribute("data-wjs-link",c),a[b].addEventListener("click",this.linksClick.bind(this))},linksClick:function(a){var b=this,c=a.target.getAttribute("data-wjs-link").match(b.linkReg);b.loadersExists(c[1],function(){b.loaders[c[1]].link(c[2])});
return!1},loaderAdd:function(a,b,c){b=b||{};if(!this.loaders[a]){var d="WjsLoader"+a;b.type=a;b.classExtends=b.classExtends||"WjsLoader";this.classExtend(d,b);this.loaders[a]=new (this.classProto(d))(a);this.extRequire[a]={};this.extLoaded[a]=this.extLoaded[a]||{};c&&(this.extLoaded.WjsLoader[a]=b)}},loadersExists:function(a,b){a=Array.isArray(a)?a:[a];var c,d=[];for(c=0;c<a.length;c++)if(!this.loaders[a[c]])if(this.loadersExtra.indexOf(a[c]))d.push(a[c]);else return!1;return 0<d.length?this.use({WjsLoader:d},
b):b()},use:function(a,b,c){var d=this;if("string"===typeof a){var e={};e[a]=[b];b=d.extendOptions(c,{mainType:a,mainName:b});return d.use(e,b)}return d.loadersExists(Object.keys(a),function(){b=d.extendOptions(b);var c,e,h,k,f,l,m,p=Object.keys(a),n=new d.processProto(b);for(c=0;c<p.length;c++){k=p[c];l=[];for(e=0;e<a[k].length;e++){f=a[k][e];for(h=0;h<d.destroyQ.length;h++)if(d.destroyQ[h]["#items"][k]&&d.destroyQ[h]["#items"][k][f]){d.destroyQ[h]["#callbacks"].push(function(){return d.use(a,b)});
return}!0!==b.reload&&!1!==d.loaders[k].preventReload||d.destroy(k,f,!0);h=d.get(k,f);if(!h){for(h=0;h<d.processes.length;h++)if(m=d.processes[h],m.parseQ[k]&&m.parseQ[k][f])return n.loadingComplete(!0),m.responseParseItem(k,f,function(){return d.use(a,b)});l.push(f)}}d.loaders[k].extRequestInit(l,n,b)}n.loadingStart();if(b.mainType)return d.get(b.mainType,b.mainName)})},get:function(a,b){var c=this.extLoaded[a];return c&&c.hasOwnProperty(b)?c[b]:!1},destroy:function(a,b,c){var d={"#items":{},"#callbacks":[]};
this.destroyQ.push(d);this.destroyEnqueue(d,a,b,c);this.destroyNext(d)},destroyEnqueue:function(a,b,c,d){if(this.get(b,c)&&("WjsLoader"!==b||"WjsLoader"!==c&&"JsLink"!==c&&-1===this.loadersBasic.indexOf(c))){var e,g,f,h=this.extRequire[b][c];a["#items"][b]=a["#items"][b]||{};a["#items"][b][c]=!0;if(h&&d)for(f=Object.keys(h),e=0;e<f.length;e++)for(g=0;g<h[f[e]].length;g++)this.requireShared(b,c,f[e],h[f[e]][g])||this.destroyEnqueue(a,f[e],h[f[e]][g],d);delete this.extRequire[b][c]}},requireShared:function(a,
b,c,d){var e=Object.keys(this.extRequire),g,f,h;for(f=0;f<e.length;f++)for(g=Object.keys(this.extRequire[e[f]]),h=0;h<g.length;h++)if(e[f]!==a&&g[h]!==b&&this.extRequire[e[f]][g[h]][c]&&-1!==this.extRequire[e[f]][g[h]][c].indexOf(d))return!0;return!1},destroyNext:function(a){var b=this.extLoaded,c=this.queueNext(a["#items"]),d=c.type,e=c.name;c?(b=this.loaders[d].destroy(e,b[d][e],a))&&this.destroyNextComplete(a):(this.destroyQ.splice(this.destroyQ.indexOf(a),1),this.callbacks(a["#callbacks"]))},
destroyNextComplete:function(a){var b=this.extLoaded,c=this.queueNext(a["#items"]);this.queueRem(a["#items"],c.type,c.name);delete b[c.type][c.name];this.destroyNext(a)},queueRem:function(a,b,c){delete a[b][c];this.objectIsEmpty(a[b])&&delete a[b]},queueNext:function(a){var b=Object.keys(a)[0],c;return b&&(c=Object.keys(a[b])[0])?{type:b,name:c,data:a[b][c]}:!1},ajax:function(a){a.method=a.method||"GET";a.async=a.async||!1;var b=new this.window.XMLHttpRequest;b.open(a.method,a.url,a.async);b.onreadystatechange=
function(){4===b.readyState&&(200===b.status?a.success&&"function"===typeof a.success&&a.success(b):a.error(b))};"POST"===a.method&&b.setRequestHeader("Content-type","application/x-www-form-urlencoded");b.send(a.data?this.param(a.data):void 0)},param:function(a){var b,c=[],d=Object.keys(a);for(b=0;b<d.length;b++)c.push(d[b]+"="+a[d[b]]);return c.join("&")},extendObject:function(a,b,c){for(var d=0,e=Object.keys(b),g;d<e.length;d++)g=e[d],c&&"object"===typeof b[g]?(a[g]=a[g]||{},this.extendObject(a[g],
b[g])):a[g]=b[g];return a},extendOptions:function(a,b){a?"function"===typeof a&&(a={complete:a}):a={};return b?this.extendObject(a,this.extendOptions(b)):a},extendProto:function(a,b){var c,d=Object.keys(b);for(c=0;c<d.length;c++)Object.defineProperty(a,d[c],Object.getOwnPropertyDescriptor(b,d[c]));return a},objectIsEmpty:function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},classExtend:function(a,b){this.classMethods[a]?this.extendProto(this.classMethods[a],b):this.classMethods[a]=
b},classProto:function(a){if(!this.classProtos[a]){var b,c=Object;(b=(b=this.classMethods[a])&&b.classExtends?b.classExtends:!1)&&(c=this.classProto(b));b=this.classProtos[a]=function(){return this.__construct?this.__construct.apply(this,arguments):null};b.prototype=Object.create(c.prototype);this.extendObject(b.prototype,{constructor:c,className:a,wjs:this})}this.classMethods[a]&&this.extendProto(this.classProtos[a].prototype,this.classMethods[a]);return this.classProtos[a]},classProtoDestroy:function(a){this.classProtos[a]&&
delete this.classProtos[a];this.classMethods[a]&&delete this.classMethods[a]},cacheHandle:function(a,b,c){var d=this.loaders[a].cacheHandler[b],e=this.cacheBuffer;d?d.cacheHandle(a,b,c):(e[a]=e[a]||{},e[a][b]=c)},onload:function(a,b){var c=!1,d=function(){c=!0;a.removeEventListener("load",d);b()};a.addEventListener("load",d);this.window.setTimeout(function(){c||b()},200)},err:function(a,b){if(!b&&this.window.console)this.window.console.error("[wjs error] : "+a);else throw Error("[wjs error] : "+a);
}},f["wjs-[$version]"]=new l,f.wjs||(f.wjs=f["wjs-[$version]"]),f.wjs.classExtend("WjsLoader",{type:"",preventReload:!0,processType:"server",__construct:function(){this.cacheHandler={}},__destruct:function(){},init:function(){},parse:function(a,b,c){return b},link:function(a){this.wjs.use(this.type,a)},destroy:function(a,b){return!0},extRequestInit:function(a,b){for(var c=0;c<a.length;c++)b.extRequestAdd({mode:this.processType,type:this.type,name:a[c]})}}),l=function(a){a=a||{};f.wjs.extendObject(this,
{wjs:f.wjs,parseQ:{},async:a.async||!1,callbacks:a.complete?[a.complete]:[],loadingStarted:!1,extRequests:[],exclude:a.exclude,mainType:a.mainType,mainName:a.mainName});this.wjs.processes.push(this)},l.prototype={extRequestAdd:function(a){!1===this.loadingStarted?this.extRequests.push(a):this.wjs.err("Try to add extensions request after process start.")},loadingStart:function(){var a,b,c=this,d=c.wjs,e=c.extRequests,g,f=d.settings,h={},k={};c.loadingStarted=!0;for(a=0;a<e.length;a++)switch(g=e[a],
g.mode){case "server":b=f.paramInc+"["+g.type+"]";h[b]=h[b]?h[b]+","+g.name:g.name;break;case "parse":k[g.type]=k[g.type]||{},k[g.type][g.name]={"#data":g.data}}if(d.objectIsEmpty(h))c.responseParse(k);else{if(c.exclude)if(!0===c.exclude)h[f.paramExc]="1";else for(b=Object.keys(c.exclude),a=0;a<b.length;a++)h[f.paramExc+"["+b[a]+"]"]=c.exclude[b[a]].join(",");d.ajax({url:f.responsePath+"?"+d.param(h)+f.paramExtra,method:"GET",async:c.async,success:function(a){d.extendObject(k,JSON.parse(a.responseText),
!0);c.responseParse(k)}})}},loadingComplete:function(a){var b=this.wjs;b.processes.splice(b.processes.indexOf(this),1);a||b.callbacks(this.callbacks,[b.get(this.mainType,this.mainName)]);Object.freeze(this)},responseParse:function(a){var b=this;b.wjs.extendObject(b.parseQ,a,!0);b.wjs.loadersExists(Object.keys(b.parseQ),function(){b.responseParseNext()})},responseParseNext:function(){for(var a=this.wjs,b;b=a.queueNext(this.parseQ);)if(a.get(b.type,b.name))a.queueRem(this.parseQ,b.type,b.name);else{this.responseParseItem(b.type,
b.name);return}0<Object.keys(this.parseQ).length&&this.wjs.err("Parse queue not empty.");this.loadingComplete()},responseParseItem:function(a,b,c){var d=this,e=d.wjs,g=d.parseQ[a][b];c&&(g["#callbacks"]=g["#callbacks"]||[],g["#callbacks"].push(c));if(void 0!==g["#require"]&&(e.extRequire[a][b]=e.extRequire[a][b]||{},e.extendObject(e.extRequire[a][b],g["#require"]),d.requireMissing(g["#require"]))){c=g["#require"];g["#require"]=void 0;e.use(c,function(){d.responseParseItem(a,b)});return}"string"===
typeof g["#data"]&&0===g["#data"].indexOf("cache://")?e.cacheBuffer[a]&&e.cacheBuffer[a][b]?d.cacheHandle(a,b,e.cacheBuffer[a][b]):e.loaders[a].cacheHandler[b]=d:d.cacheHandle(a,b,g["#data"])},cacheHandle:function(a,b,c){var d=this.wjs,e=d.loaders[a],g=d.cacheBuffer[a],f=e.cacheHandler;c=e.parse(b,c,this);f[b]&&delete f[b];g&&g[b]&&(delete g[b],d.objectIsEmpty(g)&&delete d.cacheBuffer[a]);!1!==c&&this.parseItemComplete(a,b,c)},requireMissing:function(a){var b,c,d=Object.keys(a);for(b=0;b<d.length;b++)for(c=
0;c<a[d[b]].length;c++)if(!1===this.wjs.get(d[b],a[d[b]][c]))return!0;return!1},parseItemComplete:function(a,b,c){var d=this.parseQ[a][b]["#callbacks"];this.wjs.extLoaded[a][b]=c;this.wjs.queueRem(this.parseQ,a,b);d?this.wjs.callbacks(d):this.responseParseNext()}},f.wjs.processProto=l,f.wjs.loaderAdd("JsLink",{processType:"parse",destroy:function(a,b){b.parentNode.removeChild(b);return!0},parse:function(a,b,c){var d=this.type,e=this.wjs.document.createElement("script");b=b||a;this.wjs.onload(e,function(){c.parseItemComplete(d,
a,e)});e.setAttribute("src",b);this.wjs.document.head.appendChild(e);return!1}},!0),f.wjs.loaderAdd("WjsLoader",{classExtends:"WjsLoaderJsLink",processType:"server",extRequestInit:function(){this.wjs.classMethods.WjsLoader.extRequestInit.apply(this,arguments)},destroy:function(a){var b=this.wjs;b.loaders[a].__destruct();b.classProtoDestroy("WjsLoader"+a);delete b.loaders[a];delete b.extLoaded[a];delete b.extRequire[a];return!0},parse:function(a,b,c){var d=this.wjs;c.callbacks.push(function(){d.loaders[a].init()});
if(!0===b)this.wjs.loaderAdd(a);else return this.wjs.loaders.JsLink.parse.apply(this,[a,b,c])}},!0)})(q)})(jQuery);
