(function(q){(function(f){var h;if(void 0===f.wjs||"3.1.1"!==f.wjs.version)h=function(){this.extendObject(this,{context:f,window:f.window||window,document:f.document||window.document,version:"3.1.1",readyCallbacks:[],readyComplete:!1,packageDefault:null,loaders:{},loadersExtra:[],loadersBuffer:{},loadersBasic:{},extLoaded:{WjsLoader:{}},extRequire:{},processProto:null,processes:[],classProtos:{},classMethods:{},settings:null,pull:this.extPull});this.context.wjsContext=f},h.prototype={init:function(a){var b=
this;this.window.addEventListener("load",function(){b.extendObject(b,a);var c,d=b.loadersBuffer;delete b.loadersBuffer;for(c in d)d.hasOwnProperty(c)&&b.loaderAdd(c,d[c],!0);c=0;for(d=b.loadersBasic.length;c<d;c++)b.loaderAdd(b.loadersBasic[c],void 0,!0);delete b.loadersBasic;(new b.processProto({complete:function(){delete b.packageDefault;b.readyComplete=!0;b.callbacks(b.readyCallbacks)}})).responseParse(b.packageDefault)})},ready:function(a){!0===this.readyComplete?a():this.readyCallbacks.push(a)},
callbacks:function(a,b){for(var c=0;c<a.length;c++)a[c].apply(this,b)},loaderAdd:function(a,b,c){b=b||{};if(void 0!==this.loadersBuffer)this.loadersBuffer[a]=b;else if(!this.loaders[a]){var d="WjsLoader"+a;b.type=a;b.classExtends=b.classExtends||"WjsLoader";this.classExtend(d,b);this.loaders[a]=new (this.classProto(d))(a);this.extRequire[a]={};this.extLoaded[a]=this.extLoaded[a]||{};c&&(this.extLoaded.WjsLoader[a]=b)}},loadersExists:function(a,b){a=Array.isArray(a)?a:[a];var c,d=a.length,e=[];for(c=
0;c<d;c++)if(!this.loaders[a[c]])if(this.loadersExtra.indexOf(a[c]))e.push(a[c]);else return!1;return 0<e.length?this.pull({WjsLoader:e},b):b()},extPull:function(a,b,c){var d=this;if("string"===typeof a){var e={};e[a]=[b];b=d.extendOptions(c,{mainType:a,mainName:b});return d.pull(e,b)}return d.loadersExists(Object.keys(a),function(){b=d.extendOptions(b);var c,e,f,g,l,h,m,p=Object.keys(a),n=new d.processProto(b);for(c=0;c<p.length;c++){g=p[c];h=[];for(e=0;e<a[g].length;e++)if(l=a[g][e],f=d.extGet(g,
l),!f||!1===d.loaders[g].preventReload||!0===b.reload){for(f=0;f<d.processes.length;f++)if(m=d.processes[f],m.parseQ[g]&&m.parseQ[g][l])return n.loadingComplete(!0),m.responseParseItem(g,l,function(){return d.extPull(a,b)});h.push(l)}d.loaders[g].extRequestInit(h,n,b)}n.loadingStart();if(b.mainType)return d.extGet(b.mainType,b.mainName)})},extPullMultiple:function(a){var b,c;for(b in a)if(a.hasOwnProperty(b))for(c=0;c<arguments.length;c++)this.extPull(b,a[b][c])},extGet:function(a,b){var c=this.extLoaded[a];
return c&&c.hasOwnProperty(b)?c[b]:!1},extDestroy:function(a,b,c){if(this.extGet(a,b)){var d,e=this.extRequire[a][b];if(e&&c){for(d in e)if(e.hasOwnProperty(d))for(c=0;c<e[d].length;c++)this.extDestroy(d,e[d][c]);delete this.extRequire[a][b]}this.loaders[a].extDestroy(b,this.extLoaded[a][b]);delete this.extLoaded[a][b]}},ajax:function(a){a.method=a.method||"GET";a.async=a.async||!1;var b=new this.window.XMLHttpRequest;b.open(a.method,a.url,a.async);b.onreadystatechange=function(){4===b.readyState&&
(200===b.status?a.success&&"function"===typeof a.success&&a.success(b):a.error(b))};"POST"===a.method&&b.setRequestHeader("Content-type","application/x-www-form-urlencoded");this.trigger("wjsXhr");b.send(this.param(a.data))},param:function(a){var b,c=[];for(b in a)a.hasOwnProperty(b)&&c.push(b+"="+a[b]);return c.join("&")},extendObject:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a},extendOptions:function(a,b){a?"function"===typeof a&&(a={complete:a}):a={};return b?this.extendObject(a,
this.extendOptions(b)):a},extendProto:function(a,b){for(var c in b)b.hasOwnProperty(c)&&Object.defineProperty(a,c,Object.getOwnPropertyDescriptor(b,c));return a},objectIsEmpty:function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},classExtend:function(a,b){this.classMethods[a]?this.extendProto(this.classMethods[a],b):this.classMethods[a]=b},classProto:function(a){if(!this.classProtos[a]){var b,c=Object;(b=(b=this.classMethods[a])&&b.classExtends?b.classExtends:!1)&&(c=this.classProto(b));
b=this.classProtos[a]=function(){return this.__construct?this.__construct.apply(this,arguments):null};b.prototype=Object.create(c.prototype);this.extendObject(b.prototype,{constructor:c,className:a,wjs:this})}this.classMethods[a]&&this.extendProto(this.classProtos[a].prototype,this.classMethods[a]);return this.classProtos[a]},classProtoDestroy:function(a){this.classProtos[a]&&delete this.classProtos[a];this.classMethods[a]&&delete this.classMethods[a]},trigger:function(a){var b=this.document.createEvent("Event");
b.initEvent(a,!0,!0);this.window.dispatchEvent(b)},err:function(a,b){if(!b&&this.window.console)this.window.console.error("[wjs error] : "+a);else throw Error("[wjs error] : "+a);}},f["wjs-3.1.1"]=new h,f.wjs||(f.wjs=f["wjs-3.1.1"]),f.wjs.classExtend("WjsLoader",{type:"undefined",preventReload:!0,processType:"server",__construct:function(){for(this.parseHook="parse"+this.type;"string"===typeof this.parseHook;)this.parseHook=this[this.parseHook]||!1},extRequestInit:function(a,b){for(var c=
0;c<a.length;c++)b.extRequestAdd({mode:this.processType,type:this.type,name:a[c]})},extDestroy:function(a,b){},responseParseItem:function(a,b,c){if(void 0!==b["#require"]&&(this.wjs.extRequire[this.type][a]=this.wjs.extRequire[this.type][a]||{},this.wjs.extendObject(this.wjs.extRequire[this.type][a],b["#require"]),this.requireMissing(b["#require"]))){a=b["#require"];b["#require"]=void 0;this.wjs.extPullMultiple(a);return}b=b["#data"];this.parseHook&&(b=this.parseHook(a,b,c));!1!==b&&c.parseItemComplete(this.type,
a,b)},requireMissing:function(a){var b,c,d;for(b in a)if(a.hasOwnProperty(b))for(c=0,d=a[b].length;c<d;c++)if(!1===this.wjs.extGet(b,a[b][c]))return!0;return!1}}),h=function(a){a=a||{};f.wjs.extendObject(this,{wjs:f.wjs,parseQ:{},async:a.async||!1,completeCallbacks:a.complete,loadingStarted:!1,extRequests:[],exclude:a.exclude,mainType:a.mainType,mainName:a.mainName});this.wjs.processes.push(this)},h.prototype={extRequestAdd:function(a){!1===this.loadingStarted?this.extRequests.push(a):this.wjs.err("Try to add extensions request after process start.")},
loadingStart:function(){var a,b,c=this,d=c.extRequests,e,f,h=this.wjs.settings,k={},g={};c.loadingStarted=!0;for(a=0;a<c.extRequests.length;a++)switch(e=d[a],e.mode){case "server":f="wjs["+a+"][";k[f+h.requestVariableKeyType+"]"]=e.type;k[f+h.requestVariableKeyName+"]"]=e.name;if(c.exclude)if(!0===c.exclude)k[f+h.requestVariableKeyExclude+"]"]="1";else for(b in c.exclude)k[f+h.requestVariableKeyExclude+"]["+b+"]"]=c.exclude[b].join(",");break;case "parse":void 0===g[e.type]&&(g[e.type]={}),g[e.type][e.name]=
{"#data":e.data}}c.wjs.objectIsEmpty(k)?c.responseParse(g):c.wjs.ajax({url:c.wjs.settings.responsePath+"?"+c.wjs.param(k)+c.wjs.settings.responseQueryExtraParam,method:"GET",async:c.async,success:function(a){c.wjs.extendObject(g,JSON.parse(a.responseText));c.responseParse(g)}})},loadingComplete:function(a){this.wjs.processes.splice(this.wjs.processes.indexOf(this),1);!a&&this.completeCallbacks&&this.wjs.callbacks([this.completeCallbacks],[this.wjs.extGet(this.mainType,this.mainName)]);Object.freeze(this)},
responseParse:function(a){this.wjs.extendObject(this.parseQ,a);this.responseParseNext()},responseParseNext:function(){var a,b,c=this.parseQ;for(a in c)if(c.hasOwnProperty(a)&&this.wjs.loaders[a])for(b in c[a])if(c[a].hasOwnProperty(b)){this.responseParseItem(a,b);return}this.wjs.objectIsEmpty(c)||this.wjs.err("Parse queue not empty.");this.loadingComplete()},responseParseItem:function(a,b,c){var d=this.parseQ[a][b];c&&(d["#callbacks"]=d["#callbacks"]||[],d["#callbacks"].push(c));this.wjs.loaders[a].responseParseItem(b,
d,this)},parseItemComplete:function(a,b,c){var d=this.parseQ[a];this.wjs.extLoaded[a][b]=c;d[b]["#callbacks"]&&this.wjs.callbacks(d[b]["#callbacks"]);delete d[b];this.wjs.objectIsEmpty(this.parseQ[a])&&delete this.parseQ[a];this.responseParseNext()}},f.wjs.processProto=h,f.wjs.loaderAdd("JsLink",{processType:"parse",extDestroy:function(a,b){b.parentNode.removeChild(b)},parseJsLink:function(a,b,c){var d=this.type,e=this.wjs.document.createElement("script");e.onload=function(){c.parseItemComplete(d,
a,e)};e.setAttribute("src",b);this.wjs.document.head.appendChild(e);return!1}}),f.wjs.loaderAdd("WjsLoader",{classExtends:"WjsLoaderJsLink",processType:"server",extRequestInit:function(){this.wjs.classMethods.WjsLoader.extRequestInit.apply(this,arguments)},extDestroy:function(a){var b=this.wjs;b.classProtoDestroy("WjsLoader"+a);delete b.loaders[a];delete b.extLoaded[a];delete b.extRequire[a]},parseWjsLoader:function(a,b,c){if(!0===b)this.wjs.loaderAdd(a);else return this.parseJsLink(a,b,c)}})})(wjsContext)})(jQuery);
